---
platform: linux

inputs:
  - name: source
  - name: version

outputs:
  - name: build
    path: source/build

caches:
  - path: source/node_modules

run:
  path: /bin/bash
  args:
    - -exc
    - |
      cp version/version source
      cd source
      make build
