---
platform: linux

inputs:
  - name: source
  - name: version

outputs:
  - name: needs-build
    path: source/build

run:
  path: /bin/bash
  args:
    - -exc
    - |
      cp version/version source
      cd source
      cat << EOF > ~/.npmrc
      fetch-timeout=300000
      always-auth=true
      email=${artifactory_auth_email}
      //usw1.packages.broadcom.com/artifactory/api/npm/npmjs/:_auth="${artifactory_auth_token}"
      EOF
      make build