---
resource_types:
  - name: pull-request
    type: registry-image
    source:
      repository: ((artifactory.registry_mirror))/teliaoss/github-pr-resource
      username: ((artifactory.production_username))
      password: ((artifactory.production_password))

resources:
  - name: oci-build-task
    type: registry-image
    check_every: 4h
    icon: oci
    source:
      repository: ((artifactory.registry_mirror))/concourse/oci-build-task
      tag: 0.11.1
      username: ((artifactory.production_username))
      password: ((artifactory.production_password))

  - name: ubuntu-image
    type: registry-image
    icon: oci
    source:
      repository: ((artifactory.registry_mirror))/ubuntu
      tag: 20.04
      username: ((artifactory.production_username))
      password: ((artifactory.production_password))

  - name: source
    type: git
    icon: github
    source:
      uri: git@github.com:cf-platform-eng/needs.git
      private_key: ((github.private_key))

  - name: pre-release
    type: github-release
    icon: github
    source:
      owner: cf-platform-eng
      repository: needs
      access_token: ((github.access_token))
      pre_release: true
      release: false

  - name: release
    type: github-release
    icon: github
    source:
      owner: cf-platform-eng
      repository: needs
      access_token: ((github.access_token))
      pre_release: false
      release: true

  - name: docker-image
    type: registry-image
    icon: docker
    source:
      repository: tas-ecosystem-docker-prod-local.usw1.packages.broadcom.com/tanzu-isv-engineering/needs
      username: ((artifactory.production_username))
      password: ((artifactory.production_password))

  - name: version
    type: semver
    source:
      driver: git
      uri: ((github.org_url))/isv-ci-versions.git
      branch: main
      username: ((github.username))
      password: ((github.broadcom_github_personal_access_token))
      file: needs

  - name: node
    type: registry-image
    icon: docker
    source:
      repository: ((artifactory.registry_mirror))/node
      username: ((artifactory.production_username))
      password: ((artifactory.production_password))
      tag: latest

  - name: pull-requests
    type: pull-request
    icon: github
    source:
      repository: cf-platform-eng/needs
      access_token: ((github.access_token))
      disable_forks: true

jobs:
  - name: test
    plan:
      - in_parallel:
        - get: node
        - get: source
          trigger: true
      - task: run-tests
        image: node
        file: source/ci/tasks/test.yml
        params:
          npm_config_registry: https://usw1.packages.broadcom.com/artifactory/api/npm/npmjs/
          artifactory_auth_token: ((broadcom_jfrog.auth_token))
          artifactory_auth_email: ((broadcom_jfrog.auth_email))
      - task: run-feature-tests
        image: node
        file: source/ci/tasks/test-features.yml
        params:
          npm_config_registry: https://usw1.packages.broadcom.com/artifactory/api/npm/npmjs/
          artifactory_auth_token: ((broadcom_jfrog.auth_token))
          artifactory_auth_email: ((broadcom_jfrog.auth_email))

  - name: build
    serial_groups: [version]
    plan:
      - in_parallel:
        - get: node
          passed:
            - test
        - get: source
          passed:
            - test
          trigger: true
        - get: version
          params: { pre: rc }
      - task: build
        image: node
        file: source/ci/tasks/build.yml
        params:
          npm_config_registry: https://usw1.packages.broadcom.com/artifactory/api/npm/npmjs/
          artifactory_auth_token: ((broadcom_jfrog.auth_token))
          artifactory_auth_email: ((broadcom_jfrog.auth_email))
      - task: test-version
        image: node
        params:
          npm_config_registry: https://usw1.packages.broadcom.com/artifactory/api/npm/npmjs/
          artifactory_auth_token: ((broadcom_jfrog.auth_token))
          artifactory_auth_email: ((broadcom_jfrog.auth_email))
        config:
          platform: linux
          inputs:
            - name: build
          run:
            path: bash
            dir: build
            args:
            - -exc
            - ./needs-linux --version
      - put: version
        inputs: detect
        params: { file: version/version }
      - in_parallel:
        - put: pre-release
          inputs: detect
          params:
            name: version/version
            tag: version/version
            globs:
              - build/*
        - do:
          - file: version/version
            load_var: image_version
          - get: ubuntu-image
            params:
              format: oci
          - get: oci-build-task
          - task: build-oci
            privileged: true
            image: oci-build-task
            config:
              platform: linux
              inputs:
                - name: source
                - name: needs-build
                - name: ubuntu-image
              outputs:
                - name: image
              params:
                CONTEXT: .
                DOCKERFILE: source/Dockerfile
                IMAGE_ARG_ubuntu_image: ubuntu-image/image.tar
              run:
                path: build
            output_mapping:
              image: docker-image-out
          - put: docker-image
            inputs: detect
            attempts: 3
            params:
              image: docker-image-out/image.tar
              version: ((.:image_version))

  - name: release
    serial_groups: [version]
    plan:
      - in_parallel:
        - get: node
          passed:
            - build
        - get: source
          passed:
            - build
        - get: version
          params: { bump: final }
      - task: build
        image: node
        file: source/ci/tasks/build.yml
        params:
          npm_config_registry: https://usw1.packages.broadcom.com/artifactory/api/npm/npmjs/
          artifactory_auth_token: ((broadcom_jfrog.auth_token))
          artifactory_auth_email: ((broadcom_jfrog.auth_email))
      - in_parallel:
        - put: release
          inputs: detect
          params:
            name: version/version
            tag: version/version
            globs:
              - build/*
        - do:
            - file: version/version
              load_var: image_version
            - get: ubuntu-image
              params:
                format: oci
            - get: oci-build-task
            - task: build-oci
              privileged: true
              image: oci-build-task
              config:
                platform: linux
                inputs:
                  - name: source
                  - name: needs-build
                  - name: ubuntu-image
                outputs:
                  - name: image
                params:
                  CONTEXT: .
                  DOCKERFILE: source/Dockerfile
                  IMAGE_ARG_ubuntu_image: ubuntu-image/image.tar
                run:
                  path: build
              output_mapping:
                image: docker-image-out
            - put: docker-image
              inputs: detect
              attempts: 3
              params:
                image: docker-image-out/image.tar
                version: ((.:image_version))
                bump_aliases: true
      - put: version
        inputs: detect
        params: { bump: patch }

  - name: bump-major-version
    serial_groups: [version]
    plan:
      - put: version
        inputs: detect
        params:
          bump: major

  - name: bump-minor-version
    serial_groups: [version]
    plan:
      - put: version
        inputs: detect
        params:
          bump: minor

  - name: test-pull-request
    serial: true
    plan:
      - get: node
      - get: source
        resource: pull-requests
        trigger: true
        version: every
        params:
          integration_tool: rebase
      - put: pull-requests
        inputs: detect
        params:
          path: source
          status: pending
      - task: run-tests
        image: node
        file: source/ci/tasks/test.yml
        params:
          npm_config_registry: https://usw1.packages.broadcom.com/artifactory/api/npm/npmjs/
          artifactory_auth_token: ((broadcom_jfrog.auth_token))
          artifactory_auth_email: ((broadcom_jfrog.auth_email))
        on_failure:
          put: pull-requests
          inputs: detect
          params:
            path: source
            status: failure
      - task: run-feature-tests
        image: node
        file: source/ci/tasks/test-features.yml
        params:
          npm_config_registry: https://usw1.packages.broadcom.com/artifactory/api/npm/npmjs/
          artifactory_auth_token: ((broadcom_jfrog.auth_token))
          artifactory_auth_email: ((broadcom_jfrog.auth_email))
        on_failure:
          put: pull-requests
          inputs: detect
          params:
            path: source
            status: failure
      - put: pull-requests
        inputs: detect
        params:
          path: source
          status: success
